app/app.py
from flask import Flask

from routes.chat import chat_bp
from routes.fallback import fallback_bp
from routes.index import index_bp

# -------------------------

app = Flask(__name__)

# -------------------------

"""
Blueprints Registration
"""
app.register_blueprint(chat_bp)
app.register_blueprint(fallback_bp)
app.register_blueprint(index_bp)

# -------------------------

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=7860)

app/routes/chat.py
from datetime import datetime, timezone
from flask import Blueprint, jsonify, render_template_string, request, session
from huggingface_hub import InferenceClient
from time import time, sleep
import os

from routes.utils import init_chat

# -------------------------

MODEL = 'openai/gpt-oss-20b'
LLM = InferenceClient(
    provider='groq',
    api_key=os.environ['HF_TOKEN__Chatbot'],
)

# -------------------------

chat_bp = Blueprint('chat', __name__, url_prefix='/chat')

# -------------------------

@chat_bp.route('/user-message', methods=['POST'])
def user_message():

    """
    Session Requirements
    """
    if 'chats' not in session or 'chat_id' not in session or session['chat_id'] not in session['chats']:
        init_chat()

    # -------------------------

    user_msg = request.json.get('prompt')

    # -------------------------

    session['chats'][session['chat_id']]['messages'].append({
        'role': 'user',
        'content': user_msg,
        'timestamp': datetime.now(timezone.utc).isoformat()
    })

    # -------------------------

    user_msg_html = render_template_string(
        "{% import 'includes/message.html' as macros %}{{ macros.message(msg) }}",
        msg=session['chats'][session['chat_id']]['messages'][-1]
    )

    # -------------------------

    return jsonify({ 'user_msg_html': user_msg_html })

@chat_bp.route('/bot-message', methods=['POST'])
def bot_message():

    """
    Clock
    """
    start_time = time()

    # -------------------------

    user_msg = request.json.get('prompt')
    completion = LLM.chat.completions.create(
        model=MODEL,
        messages=[{ 'role': 'user', 'content': user_msg }]
    )

    # -------------------------

    bot_msg = completion.choices[0].message.content
    session['chats'][session['chat_id']]['messages'].append({
        'role': 'bot',
        'content': bot_msg,
        'timestamp': datetime.now(timezone.utc).isoformat()
    })

    # -------------------------

    bot_msg_html = render_template_string(
        "{% import 'includes/message.html' as macros %}{{ macros.message(msg) }}",
        msg=session['chats'][session['chat_id']]['messages'][-1]
    )

    # -------------------------

    """
    Clock
    """
    elapsed_time = time() - start_time
    remaining_time = 2 - elapsed_time
    if remaining_time > 0:
        sleep(remaining_time)

    # -------------------------

    return jsonify({ 'bot_msg_html': bot_msg_html })

app/routes/fallback.py
from flask import Blueprint, render_template

# -------------------------

fallback_bp = Blueprint('fallback', __name__)

# -------------------------

def error_page(error):
    err_code = getattr(error, 'code', 500)
    err_name = getattr(error, 'name', type(error).__name__)
    err_desc = getattr(error, 'description', str(error))    

    # -------------------------

    return render_template('pages/error.html',
                           err_code=err_code,
                           err_name=err_name,
                           err_desc=err_desc), err_code

@fallback_bp.app_errorhandler(Exception)
def handle_exception(error):
    return error_page(error)

# @fallback_bp.route('/maintenance')
# @login_required
# def maintainance_page():
#     return render_template('pages/maintenance.html',
#                            current_user=current_user)

app/routes/index.py
from flask import Blueprint, render_template

from routes.utils import init_chat

# -------------------------

index_bp = Blueprint('index', __name__)

# -------------------------

@index_bp.route('/')
def page():

    """
    Session Initialization
    """
    init_chat()

    # -------------------------

    return render_template('pages/chat.html')

app/routes/utils.py
from datetime import datetime, timezone
from flask import session

def init_chat(chat_id=None):
    """
    Initialize a chat in the Flask session.

    Parameters:
        - chat_id (int): The ID of the chat to initialize. Default is None.
    """

    if 'chats' not in session:
        session['chats'] = {}

    if chat_id is None:
        chat_id = len(session['chats']) + 1

    session['chat_id'] = str(chat_id)
    chat_id_str = session['chat_id']

    if chat_id_str not in session['chats']:
        session['chats'][chat_id_str] = {
            'id': chat_id_str,
            'title': f"Chat {chat_id_str}",
            'messages': []
        }

    session.modified = True

def add_message(role, content, chat_id=None):
    """
    Add a message to the chat.

    Parameters:
        - role (str): The role of the message sender ('user' or 'bot').
        - content (str): The content of the message.
        - chat_id (int): The ID of the chat to initialize. Default is None.
    """

    if chat_id is None:
        chat_id = session.get('chat_id', 1)

    # -------------------------

    init_chat(chat_id)
    session['chats'][chat_id]['messages'].append({
        'role': role,
        'content': content,
        'timestamp': datetime.now(timezone.utc).isoformat()
    })

    session.modified = True

app/templates/base.html
<!DOCTYPE html>
<html data-bs-theme="light" lang="en">

<head>

    <!-- Meta -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    
    <!-- Theme -->
    <title>{{ theme_title }}</title>
    <meta name="theme-color" content="#96e072"/>

    <!-- Favicons -->
    <link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static', filename='img/favicons/favicon-16x16.png') }}"/>
    <link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('static', filename='img/favicons/favicon-32x32.png') }}"/>
    <link rel="apple-touch-icon" type="image/png" sizes="180x180" href="{{ url_for('static', filename='img/favicons/apple-touch-icon.png') }}"/>
    <link rel="icon" type="image/png" sizes="192x192" href="{{ url_for('static', filename='img/favicons/android-chrome-192x192.png') }}"/>
    <link rel="icon" type="image/png" sizes="512x512" href="{{ url_for('static', filename='img/favicons/android-chrome-512x512.png') }}"/>

    <!-- Font -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Special+Gothic+Expanded+One&display=swap" rel="stylesheet">

    <!-- Root -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/root.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bs-theme-overrides.css') }}">

    <!-- Libraries -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-SgOJa3DmI69IUzQ2PVdRZhwQ+dy64/BUtbMJw1MZ8t5HZApcHrRKUc4W0kG879m7" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

    <!-- Jinja :: Styles -->
    {% block styles %}{% endblock %}
</head>

<body>

    <!-- Jinja :: Content -->
    {% block content %}{% endblock %}

    <!-- Jinja :: Flash -->
    {% include 'includes/flash.html' %}

    <!-- Jinja :: Modals -->
    {% block modals %}{% endblock %}

    <!-- Jinja :: Spinner Page -->
    {% include 'includes/spinner-page.html' %}

    <!-- Libraries -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/js/bootstrap.bundle.min.js" integrity="sha384-k6d4wzSIapyDyv1kpU366/PK5hCdSbCRGRCMv+eplOQJWyd1fbcAu9OCUj5zNLiq" crossorigin="anonymous"></script>

    <!-- Components -->
    <script src="{{ url_for('static', filename='js/components/copyright.js') }}"></script>
    <script src="{{ url_for('static', filename='js/components/dropdown.js') }}"></script>
    <script src="{{ url_for('static', filename='js/components/flash.js') }}"></script>
    <script src="{{ url_for('static', filename='js/components/spinner_page.js') }}"></script>
    <script src="{{ url_for('static', filename='js/components/spinner.js') }}"></script>
    <!-- <script src="{{ url_for('static', filename='js/components/theme_mode.js') }}"></script> -->
    <script src="{{ url_for('static', filename='js/components/tooltip.js') }}"></script>

    <!-- Jinja :: Scripts -->
    {% block scripts %}{% endblock %}
</body>

</html>

app/templates/includes/flash.html
<!-- Flash -->
{% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        {% for category, message in messages %}
            <div class="alert-container">
                <div class="alert alert-{{ category }}" role="alert" data-timeout="{{ session['flash_timeout'] if 'flash_timeout' in session else 5000 }}">
                    
                    <!-- Badge -->
                    <span class="badge-icon">
                        {% if category == 'success' %}
                            <i class="bi bi-check-circle-fill fs-4"></i>
                        {% elif category == 'info' %}
                            <i class="bi bi-info-circle-fill fs-4"></i>
                        {% elif category == 'warning' %}
                            <i class="bi bi-exclamation-triangle-fill fs-4"></i>
                        {% elif category == 'danger' %}
                            <i class="bi bi-exclamation-circle-fill fs-4"></i>
                        {% endif %}
                    </span>

                    <!-- Message -->
                    <span class="ms-2">{{ message }}</span>
                </div>
            </div>
        {% endfor %}
    {% endif %}
{% endwith %}

app/templates/includes/footer.html
<!-- Footer -->
<footer class="footer w-100 p-5 bg-dark text-center text-light">
    <span id="copyright">Copyright &copy; YYYY <span class="text-primary">Chatbot</span>. All rights reserved.</span>
</footer>

app/templates/includes/message.html
<!-- Message -->
{% macro message(msg) %}
<div class="message-{{ 'user' if msg.role == 'user' else 'bot' }}">{{ msg.content }}</div>
{% endmacro %}

app/templates/includes/navbar.html
<!-- Navbar -->
<nav class="navbar w-100 px-5 py-3 bg-light">
    <a class="d-flex flex-row gap-3" href="{{ url_for('index.page') }}">
        <img src="{{ url_for('static', filename='img/chatbot-1.svg') }}" alt="Logo" width="32">
        <h1 class="navbar-brand m-0">Chatbot</h1>
    </a>
    <a class="d-flex align-items-center btn btn-primary" href="https://github.com/robertovicario/Chatbot" target="_blank">
        <span class="me-2">GitHub</span>
        <i class="bi bi-github fs-5"></i>
    </a>
</nav>

app/templates/includes/spinner-page.html
<!-- Spinner Page -->
<div id="spinner-page" class="d-flex justify-content-center align-items-center w-100 h-100 bg-body position-fixed top-0 start-0">
    <svg class="text-primary" width="100" height="100" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><style>.spinner_mHwL {animation: spinner_OeFQ .75s cubic-bezier(0.56, .52, .17, .98) infinite}.spinner_ote2 {animation: spinner_ZEPt .75s cubic-bezier(0.56, .52, .17, .98) infinite}@keyframes spinner_OeFQ {0% {cx: 4px;r: 3px}50% {cx: 9px;r: 8px}}@keyframes spinner_ZEPt {0% {cx: 15px;r: 8px}50% {cx: 20px;r: 3px}}</style><defs><filter id="spinner-gF00"><feGaussianBlur in="SourceGraphic" stdDeviation="1.5" result="y" /><feColorMatrix in="y" mode="matrix" values="1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 18 -7" result="z" /><feBlend in="SourceGraphic" in2="z" /></filter></defs><g filter="url(#spinner-gF00)"><circle class="spinner_mHwL" cx="4" cy="12" r="3" fill="currentColor" /><circle class="spinner_ote2" cx="15" cy="12" r="8" fill="currentColor" /></g></svg>
</div>

app/templates/pages/chat.html
<!-- Jinja :: Template -->
{% extends 'base.html' %}

<!-- Jinja :: Theme -->
{% set theme_title = 'Home - Chatbot' %}

<!-- Jinja :: Styles -->
{% block styles %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/pages/chat.css') }}">
{% endblock %}

<!-- Jinja :: Content -->
{% block content %}
<div class="d-flex justify-content-center align-items-center w-100 vh-100 overflow-auto dropdown-bug">
    <div class="d-flex flex-column justify-content-between align-items-center w-75 vh-100 p-5">

        <!-- Jinja :: Header -->
        {% include 'includes/header.html' %}

        <!-- Jinja :: Sidebar -->
        {% include 'includes/sidebar.html' %}

        <!-- Chat -->
        <div id="container-chat">

            <!-- Messages -->
            <div id="container-intro">
                <img class="w-50 mb-5 img-fluid" src="{{ url_for('static', filename='img/illustrations/home.svg') }}" alt="home.svg">
                <h2 class="mb-0 text-center">Ask me anything, I'm at your service 🤗</h2>
            </div>
            <div id="message-bot-loading">
                <svg class="text-light-emphasis" width="24" height="24" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><style>.spinner_I8Q1{animation:spinner_qhi1 .75s linear infinite}.spinner_vrS7{animation-delay:-.375s}@keyframes spinner_qhi1{0%,100%{r:1.5px}50%{r:3px}}</style><circle class="spinner_I8Q1" cx="4" cy="12" r="1.5" fill="currentColor"/><circle class="spinner_I8Q1 spinner_vrS7" cx="12" cy="12" r="3" fill="currentColor"/><circle class="spinner_I8Q1" cx="20" cy="12" r="1.5" fill="currentColor"/></svg>
            </div>
        </div>

        <!-- Prompt -->
        <div id="container-prompt" class="border rounded-4">
            <form>
                <textarea type="text" placeholder="Make a question" required rows="1"></textarea>
                <button id="btn-prompt-submit" class="btn btn-primary" type="button" name="btn-prompt-submit" title="Send">
                    <i class="bi bi-arrow-up"></i>
                </button>
            </form>
        </div>

        <!-- Footer -->
        <footer class="footer w-100 mt-4 text-center">
            <span id="copyright">Copyright &copy; YYYY <span class="text-primary">Chatbot</span>. All rights reserved.</span>
        </footer>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script>
    document.addEventListener('DOMContentLoaded', () => {

        /**
         * Submitting the prompt form
         */
        const form_prompt = document.querySelector('#container-prompt form');
        const textarea_prompt = document.querySelector('#container-prompt textarea');
        const btn_prompt_submit = document.querySelector('#btn-prompt-submit');
        btn_prompt_submit.addEventListener('click', async () => {

            /**
             * Checking form validity
             */
            if (!form_prompt.checkValidity()) return;
            const user_msg = textarea_prompt.value;
            textarea_prompt.value = '';
            document.querySelector('#container-intro').style = 'display: none !important';

            /////////////////////////

            /**
             * Changing the button icon to indicate processing
             */
            const btn_prompt_submit_content = btn_prompt_submit.innerHTML;
            btn_prompt_submit.innerHTML = '<i class="bi bi-stop-fill"></i>';

            /**
             * Sending user prompt to render the message
             */
            let response = await fetch('/chat/user-message', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ 'prompt': user_msg })
            });

            /////////////////////////

            /**
             * Updating the frontend with the user message
             */
            let data = await response.json();
            const container_chat = document.querySelector('#container-chat');
            const message_bot_loading = document.querySelector('#message-bot-loading');
            if (data.user_msg_html) {
                if (data.user_msg_html) {
                    container_chat.insertAdjacentHTML('beforeend', data.user_msg_html);
                    container_chat.appendChild(message_bot_loading);
                    message_bot_loading.style = 'display: flex !important';
                    container_chat.scrollTop = container_chat.scrollHeight;
                }
            }

            /////////////////////////

            /**
             * Sending user prompt to generate the bot message
             */
            await new Promise(resolve => requestAnimationFrame(resolve));
            response = await fetch('/chat/bot-message', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ 'prompt': user_msg })
            });

            /////////////////////////

            /**
             * Updating the frontend with the bot message
             */
            data = await response.json();
            if (data.bot_msg_html) {
                container_chat.insertAdjacentHTML('beforeend', data.bot_msg_html);
                message_bot_loading.style = 'display: none !important';
                container_chat.scrollTop = container_chat.scrollHeight;

                /**
                 * Typing Effect
                 */
                const bot_message_el = container_chat.querySelector('.message-bot:last-child');
                const full_text = bot_message_el.textContent;
                bot_message_el.textContent = '';

                let idx = 0;
                let typing = true;

                const truncate_typing = () => {
                    if (typing) {
                        typing = false;
                        container_chat.scrollTop = container_chat.scrollHeight;
                        btn_prompt_submit.innerHTML = btn_prompt_submit_content;
                    }
                };
                btn_prompt_submit.addEventListener('click', truncate_typing);

                function typing_effect() {
                    if (idx < full_text.length && typing) {
                        bot_message_el.textContent += full_text.charAt(idx);
                        idx++;
                        container_chat.scrollTop = container_chat.scrollHeight;
                        setTimeout(typing_effect, 20);
                    } else {
                        typing = false;
                        btn_prompt_submit.innerHTML = btn_prompt_submit_content;
                    }
                }
                typing_effect();
            }
        });

        /////////////////////////

        /**
         * Ensuring the chat container is scrolled to the bottom
         */
        const container_chat = document.querySelector('#container-chat');
        container_chat.scrollTop = container_chat.scrollHeight;

        /**
         * Auto-resizing textarea
         */
        textarea_prompt.addEventListener('input', () => {
            const min_height = 28;
            textarea_prompt.style = 'height: auto !important;';
            textarea_prompt.style = `height: ${Math.max(textarea_prompt.scrollHeight, min_height)}px !important;`;
            form_prompt.style = textarea_prompt.scrollHeight > min_height ? 'align-items: flex-end !important;' : 'align-items: center !important;';
        });

        /**
         * Submitting the form on Enter key press (without Shift)
         */
        textarea_prompt.addEventListener('keydown', (e) => {
            if (e.key === 'Enter' && !e.shiftKey) {
                e.preventDefault();
                btn_prompt_submit.click();
            }
        });
    });
</script>
{% endblock %}

app/templates/pages/error.html
<!-- Jinja :: Template -->
{% extends 'base.html' %}

<!-- Jinja :: Theme -->
{% set theme_title = 'Error Page - Chatbot' %}

<!-- Jinja :: Content -->
{% block content %}
<div class="d-flex flex-column justify-content-between align-items-center w-100 vh-100 overflow-auto">

    <!-- Jinja :: Navbar -->
    {% include 'includes/navbar.html' %}

    <!-- Content -->
    <div class="d-flex flex-column justify-content-center align-items-center text-center">
        <img class="w-25 mb-4 img-fluid" src="{{ url_for('static', filename='img/illustrations/error.svg') }}" alt="error.svg">
        <h2 class="text-danger w-50 mb-2">Error&nbsp;<span>{{ err_code }}:&nbsp;{{ err_name }}</span></h2>
        <p class="text-dark w-75 mb-4">{{ err_desc }}</p>
        <a class="btn btn-danger" href="{{ url_for('index.page') }}">Come Back</a>
    </div>

    <!-- Jinja :: Footer -->
    {% include 'includes/footer.html' %}
</div>
{% endblock %}

app/templates/pages/home.html
<!-- Jinja :: Template -->
{% extends 'base.html' %}

<!-- Jinja :: Theme -->
{% set theme_title = 'Home - Chatbot' %}

<!-- Jinja :: Styles -->
{% block styles %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/pages/home.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='css/components/chat.css') }}">
{% endblock %}

<!-- Jinja :: Content -->
{% block content %}

<!-- Jinja :: Spinner Page -->
{% include 'includes/spinner-page.html' %}

<div class="d-flex justify-content-center align-items-center w-100 vh-100 p-5 gap-5">

    <!-- Sidebar -->
    <div class="bg-white w-25 h-100 p-3 border d-none d-md-block"></div>

    <!-- Content -->
    <div class="bg-white w-100 w-md-75 h-100">
        <div class="d-flex flex-column justify-content-center align-items-center h-100">

            <!-- Chat -->
            <div id="container-chat">
                {% import 'includes/message.html' as macros %}
                {% for msg in conversation %}
                    {{ macros.message(msg) }}
                {% endfor %}
                <div id="message-bot-loading">
                    <svg class="text-light-emphasis" width="24" height="24" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><style>.spinner_I8Q1{animation:spinner_qhi1 .75s linear infinite}.spinner_vrS7{animation-delay:-.375s}@keyframes spinner_qhi1{0%,100%{r:1.5px}50%{r:3px}}</style><circle class="spinner_I8Q1" cx="4" cy="12" r="1.5" fill="currentColor"/><circle class="spinner_I8Q1 spinner_vrS7" cx="12" cy="12" r="3" fill="currentColor"/><circle class="spinner_I8Q1" cx="20" cy="12" r="1.5" fill="currentColor"/></svg>
                </div>
            </div>

            <!-- Prompt -->
            <div id="container-prompt" class="border">
                <form>
                    <textarea type="text" placeholder="Ask me anything you want, I am at your service" required rows="1"></textarea>
                    <button id="btn-prompt-submit" class="btn btn-primary" type="button" name="btn-prompt-submit" title="Send">
                        <i class="bi bi-arrow-up"></i>
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script>
    document.addEventListener('DOMContentLoaded', () => {

        /**
         * Submitting the prompt form
         */
        const form_prompt = document.querySelector('#container-prompt form');
        const textarea_prompt = document.querySelector('#container-prompt textarea');
        const btn_prompt_submit = document.getElementById('btn-prompt-submit');
        btn_prompt_submit.addEventListener('click', async () => {

            /**
             * Checking form validity
             */
            if (!form_prompt.checkValidity()) return;
            const user_msg = textarea_prompt.value;
            textarea_prompt.value = '';
            btn_prompt_submit.disabled = true;

            /////////////////////////

            /**
             * Sending user prompt to render the message
             */
            let response = await fetch('/chat/user-message', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ 'prompt': user_msg })
            });

            /////////////////////////

            /**
             * Updating the frontend with the user message
             */
            let data = await response.json();
            const container_chat = document.getElementById('container-chat');
            const message_bot_loading = document.getElementById('message-bot-loading');
            if (data.user_msg_html) {
                if (data.user_msg_html) {
                    container_chat.insertAdjacentHTML('beforeend', data.user_msg_html);
                    container_chat.appendChild(message_bot_loading);
                    message_bot_loading.style = 'display: flex !important';
                    container_chat.scrollTop = container_chat.scrollHeight;
                }
            }

            /////////////////////////

            /**
             * Sending user prompt to generate the bot message
             */
            await new Promise(resolve => requestAnimationFrame(resolve));
            response = await fetch('/chat/bot-message', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ 'prompt': user_msg })
            });

            /////////////////////////

            /**
             * Updating the frontend with the bot message
             */
            data = await response.json();
            if (data.bot_msg_html) {
                container_chat.insertAdjacentHTML('beforeend', data.bot_msg_html);
                message_bot_loading.style = 'display: none !important';
                container_chat.scrollTop = container_chat.scrollHeight;

                /**
                 * Type Effect
                 */
                const bot_message_el = container_chat.querySelector('.message-bot:last-child');
                const full_text = bot_message_el.textContent;
                bot_message_el.textContent = '';

                let idx = 0;
                function type_effect() {
                    if (idx < full_text.length) {
                        bot_message_el.textContent += full_text.charAt(idx);
                        idx++;
                        container_chat.scrollTop = container_chat.scrollHeight;
                        setTimeout(type_effect, 20);
                    }
                }
                type_effect();

                btn_prompt_submit.disabled = false;
            }
        });

        /////////////////////////

        /**
         * Ensuring the chat container is scrolled to the bottom
         */
        const container_chat = document.getElementById('container-chat');
        container_chat.scrollTop = container_chat.scrollHeight;

        /**
         * Auto-resizing textarea
         */
        textarea_prompt.addEventListener('input', () => {
            const min_height = 28;
            textarea_prompt.style = 'height: auto !important;';
            textarea_prompt.style = `height: ${Math.max(textarea_prompt.scrollHeight, min_height)}px !important;`;
            form_prompt.style = textarea_prompt.scrollHeight > min_height ? 'align-items: flex-end !important;' : 'align-items: center !important;';
        });
    });
</script>
{% endblock %}